177 openapi missing embedded objects generation
sngular/scs-multiapi-plugin pull request #180
Opened 2023-03-09 11:45 UTC by 5uso-sng

Fixes #177, adding support for nested object generation.

Includes extensive changes to SchemaFieldObject types.

2023-03-13 08:14 UTC, jemacineiras requested changes

2023-03-13 11:08 UTC, josemenvegsngular commented on multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/OpenApiGenerator.java
>      properties.put(refSplit[refSplit.length - 1], basicSchema);
There are three uses of _refSplit[refSplit.length - 1]_ , may be a constant could avoid repetition.

Other point that I'm thinking about my issue (and related with this code) is if it has sense (at least in async) to work just with the name or qhith the full path (to distinguish if the reference is a message or a schema)

2023-03-13 11:23 UTC, josemenvegsngular commented on multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/model/SchemaFieldObjectType.java
> +  public boolean containsType(String type) {
Why not in one line:
`return type.equals(baseType) || Objects.nonNull(innerType) && innerType.containsType(type);`

2023-03-13 11:32 UTC, janDuinRod commented on multiapi-engine/src/test/java/com/sngular/api/generator/plugin/openapi/OpenApiGeneratorFixtures.java
> +          .clientPackage("com.sngular.multifileplugin.testCreateDto.client")
Shouldn't the Dto prefix be all caps?

2023-03-13 11:47 UTC, davidgayoso commented on multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/utils/MapperContentUtil.java
> +      schemaCombinatorType = "allOf";
I think you should create an static variable instead of "hardcoding" these values.

2023-03-13 12:05 UTC, janDuinRod reviewed
After fixing the failed checks should be good for merging

2023-03-15 08:37 UTC, jemacineiras approved these changes

2023-03-15 08:39 UTC, janDuinRod approved these changes

2023-03-15 08:40 UTC, davidgayoso approved these changes

2023-03-15 11:14 UTC, merged