Null Pointer Exception on Build when no operationId is provided
sngular/scs-multiapi-plugin pull request #239
Opened 2023-05-11 09:05 UTC by davidgayoso

Fixes #151.

2023-05-11 09:46 UTC, 5uso-sng requested changes
The change seems ok, but make sure to update the version numbers

2023-05-11 09:46 UTC, 5uso-sng commented on multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/exception/InvalidAPIException.java
> +
This new file is missing its license notice

2023-05-11 11:04 UTC, 5uso-sng submitted a review, later dismissed

2023-05-11 11:15 UTC, jemacineiras requested changes

2023-05-11 11:15 UTC, jemacineiras commented on multiapi-engine/src/main/java/com/sngular/api/generator/plugin/asyncapi/exception/InvalidAPIException.java
What happen with the Openapi side.. it should have the same behaviour always

2023-05-12 08:31 UTC, 5uso-sng commented on multiapi-engine/src/main/java/com/sngular/api/generator/plugin/openapi/exception/InvalidAPIException.java
> +  private static final String ERROR_MESSAGE = "OpenApi -> There is at least one operation without operationId";
Does it make sense to have this class duplicated in both openapi and asyncapi? We have a package for common exceptions

2023-05-15 08:41 UTC, 5uso-sng approved these changes

2023-05-15 08:42 UTC, merged